jobs:
  build_and_unit_test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build testGmsDebugUnitTest
    - continue-on-error: true
      if: ${{ always() }}
      name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
  connected_test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew connectedGmsDebugAndroidTest -x lint --stacktrace
        target: ${{ matrix.target }}
    strategy:
      matrix:
        api-level:
        - 29
        target:
        - playstore
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
